services:
  backend:
    build:
      context: ./EcommerceBE
      dockerfile: Dockerfile
    container_name: rota_backend
    ports:
      - "3000:3000"
    env_file:
      - ./EcommerceBE/.env
    volumes:
      - ./EcommerceBE:/app #montar o código do backend no container
      - /app/node_modules #evitar conflitos de node_modules entre host e container
    
  frontend:
    image: node:22-alpine
    container_name: rota_frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "8080:8080"
    volumes:
      - ./FrontEnd:/app #montar o código do frontend no container
      - /app/node_modules #evitar conflitos de node_modules entre host e container
